import { useEffect, useMemo, useState } from "react";
import { Building2, ChevronLeft, Plus, ShieldCheck, Smartphone, Star, Users, WandSparkles } from "lucide-react";
import { Link } from "wouter";

const MODULES = ["pos", "restaurant", "retail", "ktv", "beauty", "booking", "inventory", "employees", "payroll", "membership", "loyalty", "qr_ordering", "kitchen_display", "accounting", "analytics", "ai_whatsapp", "ai_telegram", "song_requests", "bottle_keep", "faq_automation", "games"];
type Company = { id:number; name:string; appName:string; industry:string; status:string; logoUrl?:string; websiteDomain?:string; subscriptionPlan:string; subscriptionStatus:string; trialEndsAt?:string; billingModel?:string; billingCycle?:string; price?:string; currency?:string; theme?:any };
type Row = Record<string, any>;

async function request(path:string, options:RequestInit = {}, companyId?:number) {
  const response = await fetch(path, { ...options, credentials:"include", headers:{ "Content-Type":"application/json", ...(companyId ? { "X-Company-Id":String(companyId) } : {}), ...(options.headers || {}) } });
  const body = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(body.message || `Request failed (${response.status})`);
  return body;
}

const field = "w-full rounded-xl border border-slate-700 bg-slate-950/70 px-3 py-2.5 text-sm text-white outline-none focus:border-cyan-400";
const button = "rounded-xl bg-cyan-400 px-4 py-2.5 text-sm font-bold text-slate-950 hover:bg-cyan-300 disabled:opacity-50";

export default function BridgeXAdmin() {
  const [companies,setCompanies] = useState<Company[]>([]);
  const [companyId,setCompanyId] = useState<number>();
  const [platformAdmin,setPlatformAdmin] = useState(false);
  const [registry,setRegistry] = useState<{key:string;name:string;category:string;status:string;desc:string}[]>([]);
  const [industries,setIndustries] = useState<{key:string;name:string;modules:string[]}[]>([]);
  const [modules,setModules] = useState<string[]>([]);
  const [branches,setBranches] = useState<Row[]>([]);
  const [positions,setPositions] = useState<Row[]>([]);
  const [staff,setStaff] = useState<Row[]>([]);
  const [leaders,setLeaders] = useState<Row[]>([]);
  const [meetings,setMeetings] = useState<Row[]>([]);
  const [attendance,setAttendance] = useState<Row[]>([]);
  const [leave,setLeave] = useState<Row[]>([]);
  const [shifts,setShifts] = useState<Row[]>([]);
  const [applications,setApplications] = useState<Row[]>([]);
  const [tenantUsers,setTenantUsers] = useState<Row[]>([]);
  const [feedback,setFeedback] = useState<Row[]>([]);
  const [suppliers,setSuppliers] = useState<Row[]>([]);
  const [items,setItems] = useState<Row[]>([]);
  const [purchaseOrders,setPurchaseOrders] = useState<Row[]>([]);
  const [customers,setCustomers] = useState<Row[]>([]);
  const [segments,setSegments] = useState<Row>({});
  const [custSearch,setCustSearch] = useState("");
  const [supForm,setSupForm] = useState({name:"",phone:"",email:""});
  const [itemForm,setItemForm] = useState({name:"",sku:"",category:"",unit:"unit",costPrice:"0",sellPrice:"0",lowStockThreshold:"0",supplierId:""});
  const [custForm,setCustForm] = useState({name:"",phone:"",email:"",birthday:"",note:""});
  const [poForm,setPoForm] = useState<{supplierId:string;note:string;lines:{itemId:string;quantity:string;unitCost:string}[]}>({supplierId:"",note:"",lines:[{itemId:"",quantity:"1",unitCost:"0"}]});
  const [access,setAccess] = useState<Row>({});
  const [settings,setSettings] = useState<any>({ loyalty:{pointsSpendRp:1000,rewardsEnabled:true,tiers:[]}, services:{}, booking:{areas:[]}, automation:{reminders:[],faq:[]} });
  const [tab,setTab] = useState("company");
  const [message,setMessage] = useState("");
  const [busy,setBusy] = useState(false);
  const [companyForm,setCompanyForm] = useState({ name:"", appName:"", adminEmail:"", industry:"restaurant", branchName:"Main Outlet", subscriptionPlan:"starter", billingModel:"subscription", billingCycle:"monthly", price:"0", modules:["pos","inventory","employees"] });
  const [branchForm,setBranchForm] = useState({ name:"", address:"" });
  const [positionName,setPositionName] = useState("");
  const [staffForm,setStaffForm] = useState({ userId:"", name:"", email:"", role:"staff", branchId:"", positionId:"", employmentType:"full_time", payType:"salary", baseSalary:"0", hourlyRate:"0", hireDate:"" });
  const [meetingForm,setMeetingForm] = useState({ title:"", startsAt:"", location:"", agenda:"" });
  const [leaveForm,setLeaveForm] = useState({ type:"leave", startDate:"", endDate:"", reason:"" });
  const [shiftForm,setShiftForm] = useState({ userId:"", shiftDate:"", startTime:"", endTime:"", role:"", note:"" });
  const [shiftDates,setShiftDates] = useState<string[]>([]);
  const [userSearch,setUserSearch] = useState("");
  const selected = useMemo(() => companies.find((c) => c.id === companyId),[companies,companyId]);
  const moduleGroups = useMemo(() => {
    const src = registry.length ? registry : MODULES.map(k=>({key:k,name:k.replaceAll("_"," "),category:"Modules",status:"live",desc:""}));
    const g:Record<string,typeof src> = {};
    src.forEach(m=>{(g[m.category]=g[m.category]||[]).push(m);});
    return g;
  },[registry]);
  const [brand,setBrand] = useState({ appName:"", logoUrl:"", appIconUrl:"", websiteDomain:"", androidPackage:"", iosBundleId:"", primaryColor:"#06b6d4", accentColor:"#f59e0b", billingModel:"subscription", billingCycle:"monthly", subscriptionPlan:"starter", price:"0", currency:"IDR" });

  async function loadCompanies() {
    const [boot,list] = await Promise.all([request("/api/v1/platform/bootstrap"),request("/api/v1/companies")]);
    setPlatformAdmin(boot.platformAdmin); setCompanies(list); setCompanyId((current) => current || list[0]?.id);
    if (boot.platformAdmin) setApplications(await request("/api/v1/platform/applications"));
  }
  async function loadTenant(id:number, hydrateForms=true) {
    const [mods,bs,ps,ss,ls,ms,wl,att,lv,sh,fb,cfg,gate] = await Promise.all([
      request("/api/v1/company/modules",{},id), request("/api/v1/company/branches",{},id), request("/api/v1/company/positions",{},id),
      request("/api/v1/company/staff",{},id), request("/api/v1/company/staff/leaderboard",{},id), request("/api/v1/company/meetings",{},id), request("/api/v1/company/white-label",{},id),
      request("/api/v1/company/attendance",{},id), request("/api/v1/company/leave",{},id), request("/api/v1/company/shifts",{},id),
      request("/api/v1/company/feedback",{},id), request("/api/v1/company/settings",{},id), request("/api/v1/company/access-status",{},id),
    ]);
    const en = mods.filter((m:Row) => m.enabled).map((m:Row) => m.moduleKey);
    setModules(en); setBranches(bs); setPositions(ps); setStaff(ss); setLeaders(ls); setMeetings(ms);
    setAttendance(att); setLeave(lv); setShifts(sh);
    setFeedback(fb); if(hydrateForms) setSettings(cfg.config || settings); setAccess(gate);
    await loadModuleData(id, en);
    if(hydrateForms) setBrand({ appName:wl.appName || "", logoUrl:wl.logoUrl || "", appIconUrl:wl.appIconUrl || "", websiteDomain:wl.websiteDomain || "", androidPackage:wl.androidPackage || "", iosBundleId:wl.iosBundleId || "", primaryColor:wl.theme?.primaryColor || "#06b6d4", accentColor:wl.theme?.accentColor || "#f59e0b", billingModel:wl.billingModel || "subscription", billingCycle:wl.billingCycle || "monthly", subscriptionPlan:wl.subscriptionPlan || "starter", price:wl.price || "0", currency:wl.currency || "IDR" });
  }
  async function loadModuleData(id:number, en:string[]) {
    try {
      if (en.includes("inventory")) { setItems(await request("/api/v1/company/inventory/items",{},id)); setSuppliers(await request("/api/v1/company/inventory/suppliers",{},id)); } else { setItems([]); setSuppliers([]); }
      if (en.includes("purchasing")) setPurchaseOrders(await request("/api/v1/company/inventory/purchase-orders",{},id)); else setPurchaseOrders([]);
      if (en.includes("crm")) { setCustomers(await request(`/api/v1/company/crm/customers?q=${encodeURIComponent(custSearch)}`,{},id)); setSegments(await request("/api/v1/company/crm/segments",{},id)); } else { setCustomers([]); setSegments({}); }
    } catch {}
  }
  useEffect(() => { loadCompanies().catch((e) => setMessage(e.message)); },[]);
  useEffect(() => { if(companyId && modules.includes("crm")) { const t=setTimeout(()=>request(`/api/v1/company/crm/customers?q=${encodeURIComponent(custSearch)}`,{},companyId).then(setCustomers).catch(()=>{}),250); return ()=>clearTimeout(t); } },[custSearch,companyId,modules]);
  useEffect(() => { Promise.all([request("/api/v1/meta/modules"),request("/api/v1/meta/industries")]).then(([m,i])=>{setRegistry(m);setIndustries(i);const preset=i.find((x:any)=>x.key===companyForm.industry);if(preset)setCompanyForm(f=>({...f,modules:preset.modules}));}).catch(()=>{}); },[]);
  useEffect(() => {
    const params = new URLSearchParams(location.search); const sessionId = params.get("session_id");
    if (params.get("checkout") === "success" && sessionId) {
      const saved = Number(localStorage.getItem("bridgexCompanyId"));
      if (saved) act(() => request("/api/v1/company/billing/confirm", { method:"POST", body:JSON.stringify({sessionId}) }, saved), "Payment confirmed and subscription activated").finally(() => history.replaceState({}, "", "/bridgex"));
    } else if (params.get("checkout") === "cancelled") { setMessage("Checkout cancelled"); history.replaceState({}, "", "/bridgex"); }
  },[]);
  useEffect(() => { if (companyId) { localStorage.setItem("bridgexCompanyId", String(companyId)); loadTenant(companyId).catch((e) => setMessage(e.message)); } },[companyId]);
  useEffect(() => { if(!companyId)return; const refresh=()=>loadTenant(companyId,false).catch(()=>{}); const timer=setInterval(refresh,5000); const stream=new EventSource(`/api/v1/company/live?companyId=${companyId}`); stream.addEventListener("change",refresh); return()=>{clearInterval(timer);stream.close()}; },[companyId]);
  useEffect(() => { if(!companyId)return; const timer=setTimeout(()=>request(`/api/v1/company/users?q=${encodeURIComponent(userSearch)}`,{},companyId).then(setTenantUsers).catch(()=>{}),250); return()=>clearTimeout(timer); },[companyId,userSearch]);
  async function act(run:()=>Promise<any>, success:string) { setBusy(true); setMessage(""); try { await run(); setMessage(success); if(companyId) await loadTenant(companyId); await loadCompanies(); } catch(e:any) { setMessage(e.message); } finally { setBusy(false); } }

  return <div className="min-h-screen overflow-x-hidden bg-[#07101f] text-slate-100">
    <header className="border-b border-white/10 bg-slate-950/70 px-5 py-4 backdrop-blur"><div className="mx-auto flex max-w-7xl flex-col items-stretch gap-3 sm:flex-row sm:items-center sm:justify-between sm:gap-4">
      <div className="flex items-center gap-3"><Link href="/"><ChevronLeft className="h-5 w-5" /></Link><div className="grid h-10 w-10 place-items-center rounded-xl bg-cyan-400 font-black text-slate-950">BX</div><div><h1 className="font-black tracking-tight">BridgeXPOS</h1><p className="text-xs text-slate-400">Multi-company control centre</p></div></div>
      <select className={field+" w-full sm:max-w-xs"} value={companyId || ""} onChange={(e) => setCompanyId(Number(e.target.value))}>{companies.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select>
    </div></header>
    <main className="mx-auto min-w-0 max-w-7xl p-3 sm:p-5">
      <section className="mb-6 grid grid-cols-2 gap-3 md:grid-cols-4">
        <Stat icon={<Building2/>} label="Companies" value={companies.length}/><Stat icon={<Users/>} label="Team" value={staff.length}/><Stat icon={<WandSparkles/>} label="Modules" value={modules.length}/><Stat icon={<ShieldCheck/>} label="Access" value={platformAdmin ? "Super admin" : "Company"}/>
      </section>
      {message && <div className="mb-5 rounded-xl border border-cyan-400/30 bg-cyan-400/10 p-3 text-sm text-cyan-100">{message}</div>}
      {companyId&&<div className={`mb-5 rounded-xl border p-3 text-sm ${access.allowed?"border-emerald-400/30 bg-emerald-400/10 text-emerald-200":"border-red-400/40 bg-red-500/10 text-red-200"}`}><b>{access.allowed?"App access enabled":"App access locked"}</b> · {access.subscriptionStatus||selected?.subscriptionStatus}{access.trialEndsAt&&` · trial ends ${new Date(access.trialEndsAt).toLocaleDateString()}`}</div>}
      <nav className="-mx-3 mb-5 flex max-w-[100vw] gap-2 overflow-x-auto px-3 pb-2 sm:mx-0 sm:max-w-full sm:px-0">{[["company","Companies"],...(platformAdmin?[["applications","Applications"]]:[]),["brand","White label & billing"],["modules","Services"],...(modules.includes("pos")?[["register","Register / Sales"]]:[]),...(modules.includes("restaurant")?[["tables","Tables"]]:[]),...(modules.includes("kitchen_display")?[["kds","Kitchen"]]:[]),...(modules.includes("inventory")?[["inventory","Inventory"]]:[]),...(modules.includes("purchasing")?[["purchasing","Purchasing"]]:[]),...(modules.includes("crm")?[["crm","Customers"]]:[]),["operations","Loyalty & automation"],["branches","Branches"],["staff","Staff & leaderboard"],["hr","Attendance & shifts"],["feedback","Feedback"],["performance","Leaderboard"],["meetings","Meetings"]].map(([id,label]) => <button key={id} onClick={() => setTab(id)} className={`whitespace-nowrap rounded-full px-4 py-2 text-sm ${tab===id?"bg-cyan-400 font-bold text-slate-950":"bg-white/5 text-slate-300"}`}>{label}</button>)}</nav>

      {tab === "company" && <Panel title="Company accounts" subtitle="Create a tenant, owner login, first branch and billing agreement.">
        <div className="grid gap-3 md:grid-cols-3">{["name","appName","adminEmail","branchName","price"].map((key) => <input key={key} className={field} placeholder={({name:"Company name",appName:"Customer-facing app name",adminEmail:"Owner email",branchName:"First branch",price:"Price"} as Record<string,string>)[key]} value={(companyForm as any)[key]} onChange={(e)=>setCompanyForm({...companyForm,[key]:e.target.value})}/>)}</div>
        <div className="mt-3 grid gap-3 md:grid-cols-4"><select className={field} value={companyForm.industry} onChange={(e)=>{const ind=e.target.value;const preset=industries.find(i=>i.key===ind);setCompanyForm({...companyForm,industry:ind,modules:preset?preset.modules:companyForm.modules});}}>{(industries.length?industries:[{key:"other",name:"Other"}]).map(x=><option key={x.key} value={x.key}>{x.name}</option>)}</select><select className={field} value={companyForm.billingModel} onChange={(e)=>setCompanyForm({...companyForm,billingModel:e.target.value,billingCycle:e.target.value==="one_time"?"one_time":"monthly"})}><option value="subscription">Subscription</option><option value="one_time">One-time payment</option></select><select className={field} value={companyForm.billingCycle} disabled={companyForm.billingModel==="one_time"} onChange={(e)=>setCompanyForm({...companyForm,billingCycle:e.target.value})}><option value="monthly">Monthly</option><option value="yearly">Yearly</option><option value="one_time">One time</option></select><select className={field} value={companyForm.subscriptionPlan} onChange={(e)=>setCompanyForm({...companyForm,subscriptionPlan:e.target.value})}><option>starter</option><option>growth</option><option>enterprise</option><option>custom</option></select></div>
        <div className="mt-3 rounded-xl border border-white/10 bg-white/[.03] p-3"><p className="mb-2 text-xs text-slate-400">This industry turns on {companyForm.modules.length} module(s) automatically (editable later in Services):</p><div className="flex flex-wrap gap-1.5">{companyForm.modules.map(k=><span key={k} className="rounded-full bg-cyan-400/10 px-2.5 py-1 text-[11px] text-cyan-200">{registry.find(r=>r.key===k)?.name||k}</span>)}</div></div>
        <button disabled={busy || !companyForm.name} className={button+" mt-4"} onClick={()=>act(async()=>{const result=await request(platformAdmin?"/api/v1/platform/companies":"/api/v1/companies",{method:"POST",body:JSON.stringify(companyForm)}); if(result.temporaryPassword) setMessage(`Company created. Temporary owner password: ${result.temporaryPassword}`); setCompanyForm({...companyForm,name:"",appName:"",adminEmail:""});},"Company created") }><Plus className="mr-1 inline h-4 w-4"/>Create company</button>
        <div className="mt-5 grid gap-3 md:grid-cols-2">{companies.map(c=><div key={c.id} className={`rounded-xl border p-4 ${c.id===companyId?"border-cyan-400/60 bg-cyan-400/5":"border-white/10 bg-white/[.03]"}`}><button className="w-full text-left" onClick={()=>setCompanyId(c.id)}><div className="flex justify-between"><b>{c.name}</b><span className={`text-xs uppercase ${c.subscriptionStatus==="active"?"text-emerald-300":c.subscriptionStatus==="trialing"?"text-amber-300":"text-red-300"}`}>{c.subscriptionStatus||c.status}</span></div><p className="mt-1 text-sm text-slate-400">{c.appName} · {c.industry} · {c.billingCycle || "monthly"}</p>{c.trialEndsAt&&<p className="mt-1 text-xs text-slate-500">Trial ends {new Date(c.trialEndsAt).toLocaleDateString()}</p>}</button>{platformAdmin&&<div className="mt-3 flex flex-wrap gap-3"><button className="text-xs text-emerald-300" onClick={()=>act(()=>request(`/api/v1/platform/companies/${c.id}`,{method:"PATCH",body:JSON.stringify({subscriptionStatus:"active"})}),"Merchant marked paid and activated")}>Mark paid</button><button className="text-xs text-amber-300" onClick={()=>act(()=>request(`/api/v1/platform/companies/${c.id}`,{method:"PATCH",body:JSON.stringify({trialDays:7})}),"Seven-day trial started")}>Give 7-day trial</button><button className="text-xs text-red-300" onClick={()=>act(()=>request(`/api/v1/platform/companies/${c.id}`,{method:"PATCH",body:JSON.stringify({subscriptionStatus:"unpaid"})}),"Merchant marked unpaid and app locked")}>Mark unpaid</button></div>}</div>)}</div>
      </Panel>}

      {tab === "applications" && <Panel title="Merchant applications" subtitle="Review what each company requested, then approve or reject its activation."><div className="space-y-3">{applications.length===0&&<p className="text-sm text-slate-500">No applications yet.</p>}{applications.map(a=><div key={a.id} className="rounded-xl border border-white/10 bg-white/[.03] p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><b>{a.company_name}</b><p className="text-sm text-slate-400">{a.contact_name} · {a.contact_email} · {a.contact_phone||"No phone"}</p><p className="mt-2 text-xs text-slate-500">{a.requirements?.outletCount||1} outlet(s) · {a.requirements?.expectedStaff||1} staff · {(a.requirements?.requestedModules||[]).join(", ")}</p>{a.requirements?.notes&&<p className="mt-2 text-sm text-slate-300">{a.requirements.notes}</p>}</div><span className="rounded-full bg-white/5 px-3 py-1 text-xs uppercase text-cyan-300">{a.status}</span></div>{a.status!=="approved"&&<div className="mt-3 flex gap-3"><button className="text-xs font-bold text-emerald-300" onClick={()=>act(()=>request(`/api/v1/platform/applications/${a.id}`,{method:"PATCH",body:JSON.stringify({status:"approved"})}),"Merchant approved")}>Approve</button><button className="text-xs font-bold text-red-300" onClick={()=>act(()=>request(`/api/v1/platform/applications/${a.id}`,{method:"PATCH",body:JSON.stringify({status:"rejected"})}),"Merchant rejected")}>Reject</button></div>}</div>)}</div></Panel>}

      {tab === "brand" && <Panel title="White-label website and app" subtitle="Use one platform to publish a separate brand, custom domain and mobile app for this company.">
        <div className="grid gap-3 md:grid-cols-2"><input className={field} placeholder="App name" value={brand.appName} onChange={e=>setBrand({...brand,appName:e.target.value})}/><input className={field} placeholder="company.example.com" value={brand.websiteDomain} onChange={e=>setBrand({...brand,websiteDomain:e.target.value})}/><input className={field} placeholder="Logo URL" value={brand.logoUrl} onChange={e=>setBrand({...brand,logoUrl:e.target.value})}/><input className={field} placeholder="Square app icon URL" value={brand.appIconUrl} onChange={e=>setBrand({...brand,appIconUrl:e.target.value})}/><input className={field} placeholder="com.company.pos (Android)" value={brand.androidPackage} onChange={e=>setBrand({...brand,androidPackage:e.target.value})}/><input className={field} placeholder="com.company.pos (iOS)" value={brand.iosBundleId} onChange={e=>setBrand({...brand,iosBundleId:e.target.value})}/><label className="text-xs text-slate-400">Primary colour<input type="color" className={field+" mt-1 h-11"} value={brand.primaryColor} onChange={e=>setBrand({...brand,primaryColor:e.target.value})}/></label><label className="text-xs text-slate-400">Accent colour<input type="color" className={field+" mt-1 h-11"} value={brand.accentColor} onChange={e=>setBrand({...brand,accentColor:e.target.value})}/></label></div>
        <div className="mt-4 grid gap-3 md:grid-cols-4"><select className={field} value={brand.billingModel} onChange={e=>setBrand({...brand,billingModel:e.target.value,billingCycle:e.target.value==="one_time"?"one_time":brand.billingCycle})}><option value="subscription">Subscription</option><option value="one_time">One-time</option></select><select className={field} value={brand.billingCycle} disabled={brand.billingModel==="one_time"} onChange={e=>setBrand({...brand,billingCycle:e.target.value})}><option value="monthly">Monthly</option><option value="yearly">Yearly</option><option value="one_time">One time</option></select><input className={field} type="number" value={brand.price} onChange={e=>setBrand({...brand,price:e.target.value})}/><select className={field} value={brand.currency} onChange={e=>setBrand({...brand,currency:e.target.value})}><option>IDR</option><option>SGD</option><option>USD</option><option>MYR</option></select></div>
        <div className="mt-4 flex flex-wrap gap-3"><button disabled={busy||!companyId} className={button} onClick={()=>act(()=>request("/api/v1/company/white-label",{method:"PUT",body:JSON.stringify({...brand,theme:{primaryColor:brand.primaryColor,accentColor:brand.accentColor}})},companyId),"Brand and commercial terms saved")}>Save white label</button><button disabled={busy||!companyId||Number(brand.price)<=0} className="rounded-xl border border-cyan-400 px-4 py-2.5 text-sm font-bold text-cyan-300 disabled:opacity-40" onClick={()=>act(async()=>{await request("/api/v1/company/white-label",{method:"PUT",body:JSON.stringify({...brand,theme:{primaryColor:brand.primaryColor,accentColor:brand.accentColor}})},companyId);const checkout=await request("/api/v1/company/billing/checkout",{method:"POST",body:"{}"},companyId);location.href=checkout.url;},"Opening secure checkout")}>Pay / start subscription</button></div>
        <div className="mt-5 rounded-2xl p-5" style={{background:brand.primaryColor}}><div className="flex items-center gap-3">{brand.logoUrl?<img src={brand.logoUrl} className="h-12 w-12 rounded-xl object-cover"/>:<Smartphone/>}<div><b className="text-slate-950">{brand.appName || selected?.name || "Your app"}</b><p className="text-xs text-slate-900/70">{brand.websiteDomain || "your-company.com"}</p></div></div></div>
      </Panel>}

      {tab === "modules" && <Panel title="Modules & industry system" subtitle="Tick the functions this business runs. Each industry starts with a preset; you can add or remove any module. Green = live now, amber = partial, grey = on the roadmap.">
        <div className="mb-4 flex flex-wrap items-center gap-2 text-xs text-slate-400"><span>Quick apply an industry preset:</span>{industries.map(i=><button key={i.key} className="rounded-full bg-white/5 px-3 py-1 text-slate-200 hover:bg-cyan-400/15" onClick={()=>setModules(i.modules)}>{i.name}</button>)}</div>
        {Object.entries(moduleGroups).map(([cat,items])=><div key={cat} className="mb-5">
          <h3 className="mb-2 text-sm font-black uppercase tracking-wider text-cyan-300">{cat}</h3>
          <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{items.map(m=>{const on=modules.includes(m.key);const badge=m.status==="live"?"bg-emerald-400/15 text-emerald-300":m.status==="beta"?"bg-amber-400/15 text-amber-300":"bg-white/10 text-slate-400";return <label key={m.key} className={`flex cursor-pointer items-start gap-3 rounded-xl border p-3 ${on?"border-cyan-400/50 bg-cyan-400/5":"border-white/10 bg-white/[.03]"}`}><input type="checkbox" className="mt-1" checked={on} onChange={()=>setModules(on?modules.filter(x=>x!==m.key):[...modules,m.key])}/><span className="min-w-0"><span className="flex items-center gap-2"><b className="text-sm">{m.name}</b><span className={`rounded-full px-2 py-0.5 text-[10px] uppercase ${badge}`}>{m.status}</span></span>{m.desc&&<span className="mt-0.5 block text-[11px] text-slate-400">{m.desc}</span>}</span></label>;})}</div>
        </div>)}
        <button className={button+" mt-2"} disabled={busy} onClick={()=>act(()=>request("/api/v1/company/modules",{method:"PUT",body:JSON.stringify({modules})},companyId),"Services updated")}>Save modules</button>
      </Panel>}

      {tab === "register" && companyId && <PosPanel companyId={companyId} customers={customers} crmOn={modules.includes("crm")} onMsg={setMessage} />}

      {tab === "tables" && companyId && <TablesPanel companyId={companyId} onMsg={setMessage} />}

      {tab === "kds" && companyId && <KdsPanel companyId={companyId} onMsg={setMessage} />}

      {tab === "inventory" && <div className="grid gap-5 lg:grid-cols-2">
        <Panel title="Stock items" subtitle="Track quantity on hand. Items at or below their low-stock level are flagged red.">
          <div className="grid gap-2 sm:grid-cols-2"><input className={field} placeholder="Item name" value={itemForm.name} onChange={e=>setItemForm({...itemForm,name:e.target.value})}/><input className={field} placeholder="SKU / barcode" value={itemForm.sku} onChange={e=>setItemForm({...itemForm,sku:e.target.value})}/><input className={field} placeholder="Category" value={itemForm.category} onChange={e=>setItemForm({...itemForm,category:e.target.value})}/><input className={field} placeholder="Unit (e.g. bottle, kg)" value={itemForm.unit} onChange={e=>setItemForm({...itemForm,unit:e.target.value})}/><input className={field} type="number" placeholder="Cost price" value={itemForm.costPrice} onChange={e=>setItemForm({...itemForm,costPrice:e.target.value})}/><input className={field} type="number" placeholder="Sell price" value={itemForm.sellPrice} onChange={e=>setItemForm({...itemForm,sellPrice:e.target.value})}/><input className={field} type="number" placeholder="Low-stock alert at" value={itemForm.lowStockThreshold} onChange={e=>setItemForm({...itemForm,lowStockThreshold:e.target.value})}/><select className={field} value={itemForm.supplierId} onChange={e=>setItemForm({...itemForm,supplierId:e.target.value})}><option value="">No supplier</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></div>
          <button className={button+" mt-3"} disabled={busy||!itemForm.name} onClick={()=>act(async()=>{await request("/api/v1/company/inventory/items",{method:"POST",body:JSON.stringify(itemForm)},companyId);setItemForm({name:"",sku:"",category:"",unit:"unit",costPrice:"0",sellPrice:"0",lowStockThreshold:"0",supplierId:""});},"Item added")}><Plus className="mr-1 inline h-4 w-4"/>Add item</button>
          <div className="mt-5 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-slate-500"><tr><th>Item</th><th>Stock</th><th>Cost/Sell</th><th></th></tr></thead><tbody>{items.length===0&&<tr><td colSpan={4} className="py-4 text-slate-500">No items yet.</td></tr>}{items.map(i=><tr key={i.id} className={`border-t border-white/10 ${i.low_stock?"bg-red-500/10":""}`}><td className="py-2">{i.name}<div className="text-xs text-slate-500">{i.sku||"—"}{i.supplier_name?` · ${i.supplier_name}`:""}</div></td><td>{Number(i.stock)} {i.unit}{i.low_stock&&<span className="ml-1 rounded bg-red-500/20 px-1.5 py-0.5 text-[10px] text-red-300">LOW</span>}</td><td className="text-xs">{Number(i.cost_price).toLocaleString()} / {Number(i.sell_price).toLocaleString()}</td><td className="whitespace-nowrap"><button className="text-xs text-emerald-300" title="Add stock" onClick={()=>{const q=prompt(`Add stock to ${i.name} (quantity)`);if(q&&Number(q))act(()=>request("/api/v1/company/inventory/adjust",{method:"POST",body:JSON.stringify({itemId:i.id,quantity:Math.abs(Number(q)),type:"in",note:"manual add"})},companyId),"Stock updated")}}>+ in</button> <button className="text-xs text-amber-300" title="Remove stock" onClick={()=>{const q=prompt(`Remove stock from ${i.name} (quantity)`);if(q&&Number(q))act(()=>request("/api/v1/company/inventory/adjust",{method:"POST",body:JSON.stringify({itemId:i.id,quantity:-Math.abs(Number(q)),type:"out",note:"manual remove"})},companyId),"Stock updated")}}>− out</button> <button className="text-xs text-red-300" onClick={()=>{if(confirm(`Delete ${i.name}?`))act(()=>request(`/api/v1/company/inventory/items/${i.id}`,{method:"DELETE"},companyId),"Item deleted")}}>del</button></td></tr>)}</tbody></table></div>
        </Panel>
        <Panel title="Suppliers" subtitle="Vendors you buy stock from. Used when raising purchase orders.">
          <div className="grid gap-2 sm:grid-cols-3"><input className={field} placeholder="Supplier name" value={supForm.name} onChange={e=>setSupForm({...supForm,name:e.target.value})}/><input className={field} placeholder="Phone" value={supForm.phone} onChange={e=>setSupForm({...supForm,phone:e.target.value})}/><input className={field} placeholder="Email" value={supForm.email} onChange={e=>setSupForm({...supForm,email:e.target.value})}/></div>
          <button className={button+" mt-3"} disabled={busy||!supForm.name} onClick={()=>act(async()=>{await request("/api/v1/company/inventory/suppliers",{method:"POST",body:JSON.stringify(supForm)},companyId);setSupForm({name:"",phone:"",email:""});},"Supplier added")}><Plus className="mr-1 inline h-4 w-4"/>Add supplier</button>
          <div className="mt-4 grid gap-2">{suppliers.length===0&&<p className="text-sm text-slate-500">No suppliers yet.</p>}{suppliers.map(s=><div key={s.id} className="flex items-center justify-between rounded-xl border border-white/10 bg-white/[.03] p-3"><div><b>{s.name}</b><p className="text-xs text-slate-400">{s.phone||"—"} · {s.email||"—"}</p></div><button className="text-xs text-red-300" onClick={()=>{if(confirm(`Delete ${s.name}?`))act(()=>request(`/api/v1/company/inventory/suppliers/${s.id}`,{method:"DELETE"},companyId),"Supplier deleted")}}>del</button></div>)}</div>
        </Panel>
      </div>}

      {tab === "purchasing" && <Panel title="Purchase orders" subtitle="Order stock from a supplier, then mark it received to add it to inventory and update cost prices.">
        <div className="rounded-xl border border-white/10 bg-white/[.03] p-4">
          <div className="grid gap-2 sm:grid-cols-2"><select className={field} value={poForm.supplierId} onChange={e=>setPoForm({...poForm,supplierId:e.target.value})}><option value="">Select supplier</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><input className={field} placeholder="Note (optional)" value={poForm.note} onChange={e=>setPoForm({...poForm,note:e.target.value})}/></div>
          <div className="mt-3 space-y-2">{poForm.lines.map((ln,idx)=><div key={idx} className="grid gap-2 sm:grid-cols-[2fr,1fr,1fr,auto]"><select className={field} value={ln.itemId} onChange={e=>setPoForm({...poForm,lines:poForm.lines.map((l,i)=>i===idx?{...l,itemId:e.target.value}:l)})}><option value="">Select item</option>{items.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select><input className={field} type="number" placeholder="Qty" value={ln.quantity} onChange={e=>setPoForm({...poForm,lines:poForm.lines.map((l,i)=>i===idx?{...l,quantity:e.target.value}:l)})}/><input className={field} type="number" placeholder="Unit cost" value={ln.unitCost} onChange={e=>setPoForm({...poForm,lines:poForm.lines.map((l,i)=>i===idx?{...l,unitCost:e.target.value}:l)})}/><button className="rounded-xl border border-white/10 px-3 text-red-300" onClick={()=>setPoForm({...poForm,lines:poForm.lines.filter((_,i)=>i!==idx)})}>×</button></div>)}</div>
          <button className="mt-2 text-sm font-bold text-cyan-300" onClick={()=>setPoForm({...poForm,lines:[...poForm.lines,{itemId:"",quantity:"1",unitCost:"0"}]})}>+ Add line</button>
          <button className={button+" mt-3 block"} disabled={busy||!poForm.lines.some(l=>l.itemId&&Number(l.quantity)>0)} onClick={()=>act(async()=>{await request("/api/v1/company/inventory/purchase-orders",{method:"POST",body:JSON.stringify({supplierId:poForm.supplierId||null,note:poForm.note,items:poForm.lines.filter(l=>l.itemId&&Number(l.quantity)>0).map(l=>({itemId:Number(l.itemId),quantity:Number(l.quantity),unitCost:Number(l.unitCost)}))})},companyId);setPoForm({supplierId:"",note:"",lines:[{itemId:"",quantity:"1",unitCost:"0"}]});},"Purchase order created")}>Create purchase order</button>
        </div>
        <div className="mt-5 grid gap-3">{purchaseOrders.length===0&&<p className="text-sm text-slate-500">No purchase orders yet.</p>}{purchaseOrders.map(p=><div key={p.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-white/10 bg-white/[.03] p-4"><div><b>PO #{p.id}</b> · {p.supplier_name||"No supplier"}<p className="text-xs text-slate-400">{p.item_count} line(s) · total {Number(p.total).toLocaleString()} · <span className={p.status==="received"?"text-emerald-300":p.status==="cancelled"?"text-red-300":"text-amber-300"}>{p.status}</span></p></div><div className="flex gap-3">{p.status!=="received"&&p.status!=="cancelled"&&<><button className="text-xs font-bold text-emerald-300" onClick={()=>act(()=>request(`/api/v1/company/inventory/purchase-orders/${p.id}/receive`,{method:"POST",body:"{}"},companyId),"Stock received")}>Receive</button><button className="text-xs text-red-300" onClick={()=>act(()=>request(`/api/v1/company/inventory/purchase-orders/${p.id}`,{method:"PATCH",body:JSON.stringify({status:"cancelled"})},companyId),"PO cancelled")}>Cancel</button></>}</div></div>)}</div>
      </Panel>}

      {tab === "crm" && <Panel title="Customers & segments" subtitle="Every profile is auto-tagged: VIP (spend ≥ 5M), New (≤30 days), Active (visited ≤30 days), Lost (no visit 90+ days), Birthday this month.">
        <div className="mb-4 grid grid-cols-3 gap-2 sm:grid-cols-6">{[["total","All"],["vip","VIP"],["new","New"],["active","Active"],["lost","Lost"],["birthday","Birthday"]].map(([k,label])=><div key={k} className="rounded-xl border border-white/10 bg-white/[.04] p-3 text-center"><b className="text-xl">{Number(segments[k]||0)}</b><p className="text-[11px] text-slate-500">{label}</p></div>)}</div>
        <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3"><input className={field} placeholder="Customer name" value={custForm.name} onChange={e=>setCustForm({...custForm,name:e.target.value})}/><input className={field} placeholder="Phone" value={custForm.phone} onChange={e=>setCustForm({...custForm,phone:e.target.value})}/><input className={field} placeholder="Email" value={custForm.email} onChange={e=>setCustForm({...custForm,email:e.target.value})}/><input className={field} type="date" value={custForm.birthday} onChange={e=>setCustForm({...custForm,birthday:e.target.value})}/><input className={field+" sm:col-span-2"} placeholder="Note / tags" value={custForm.note} onChange={e=>setCustForm({...custForm,note:e.target.value})}/></div>
        <button className={button+" mt-3"} disabled={busy||!custForm.name} onClick={()=>act(async()=>{await request("/api/v1/company/crm/customers",{method:"POST",body:JSON.stringify(custForm)},companyId);setCustForm({name:"",phone:"",email:"",birthday:"",note:""});},"Customer added")}><Plus className="mr-1 inline h-4 w-4"/>Add customer</button>
        <input className={field+" mt-4"} placeholder="Search customers by name, phone or email" value={custSearch} onChange={e=>setCustSearch(e.target.value)}/>
        <div className="mt-3 grid gap-2">{customers.length===0&&<p className="text-sm text-slate-500">No customers found.</p>}{customers.map(c=><div key={c.id} className="flex flex-wrap items-center justify-between gap-2 rounded-xl border border-white/10 bg-white/[.03] p-3"><div className="min-w-0"><div className="flex flex-wrap items-center gap-1.5"><b>{c.name}</b>{c.is_vip&&<Badge t="VIP" c="bg-amber-400/20 text-amber-300"/>}{c.is_new&&<Badge t="New" c="bg-cyan-400/20 text-cyan-300"/>}{c.is_lost&&<Badge t="Lost" c="bg-red-400/20 text-red-300"/>}{c.is_birthday&&<Badge t="🎂" c="bg-pink-400/20 text-pink-300"/>}</div><p className="text-xs text-slate-400">{c.phone||"—"} · {c.email||"—"} · spend {Number(c.total_spend).toLocaleString()} · {c.visit_count} visit(s)</p></div><div className="flex gap-3"><button className="text-xs text-cyan-300" onClick={()=>{const a=prompt(`Record a visit for ${c.name} — amount spent`);if(a!==null)act(()=>request(`/api/v1/company/crm/customers/${c.id}/visit`,{method:"POST",body:JSON.stringify({amount:Number(a)||0})},companyId),"Visit recorded")}}>+ visit</button><button className="text-xs text-red-300" onClick={()=>{if(confirm(`Delete ${c.name}?`))act(()=>request(`/api/v1/company/crm/customers/${c.id}`,{method:"DELETE"},companyId),"Customer deleted")}}>del</button></div></div>)}</div>
      </Panel>}

      {tab === "operations" && <OperationsPanel settings={settings} setSettings={setSettings} onSave={()=>act(()=>request("/api/v1/company/settings",{method:"PUT",body:JSON.stringify({config:settings})},companyId),"Loyalty, booking and automation settings saved")} />}

      {tab === "branches" && <Panel title="Branches and outlets" subtitle="Every transaction and employee can be assigned to a branch."><div className="flex gap-3"><input className={field} placeholder="Branch name" value={branchForm.name} onChange={e=>setBranchForm({...branchForm,name:e.target.value})}/><input className={field} placeholder="Address" value={branchForm.address} onChange={e=>setBranchForm({...branchForm,address:e.target.value})}/><button className={button} onClick={()=>act(()=>request("/api/v1/company/branches",{method:"POST",body:JSON.stringify(branchForm)},companyId),"Branch added")}>Add</button></div><div className="mt-4 grid gap-3 md:grid-cols-3">{branches.map(b=><Mini key={b.id} title={b.name} detail={`${b.code} · ${b.address||"No address"}`}/>)}</div></Panel>}

      {tab === "staff" && <Panel title="Staff, roles, positions and pay" subtitle="Promote an existing app user or create a new staff account. Company admins only manage their own company; super admins can switch merchants above.">
        <div className="mb-4 flex gap-3"><input className={field} placeholder="New position, e.g. Barista" value={positionName} onChange={e=>setPositionName(e.target.value)}/><button className={button} onClick={()=>act(()=>request("/api/v1/company/positions",{method:"POST",body:JSON.stringify({name:positionName})},companyId),"Position added")}>Add position</button></div>
        <div className="mb-4 rounded-xl border border-white/10 bg-white/[.03] p-4"><label className="text-xs text-slate-400">Find an existing app user<input className={field+" mt-1"} placeholder="Search name or email" value={userSearch} onChange={e=>setUserSearch(e.target.value)}/></label><select className={field+" mt-2"} value={staffForm.userId} onChange={e=>{const u=tenantUsers.find(x=>x.id===e.target.value);setStaffForm({...staffForm,userId:e.target.value,email:u?.email||"",name:[u?.first_name,u?.last_name].filter(Boolean).join(" ")})}}><option value="">Or create a new user below</option>{tenantUsers.map(u=><option key={u.id} value={u.id}>{[u.first_name,u.last_name].filter(Boolean).join(" ")||u.email} · {u.email}{u.company_role?` · ${u.company_role}`:""}</option>)}</select></div>
        <div className="grid gap-3 md:grid-cols-4"><input className={field} placeholder="Staff name" value={staffForm.name} onChange={e=>setStaffForm({...staffForm,name:e.target.value})}/><input className={field} placeholder="Email" value={staffForm.email} onChange={e=>setStaffForm({...staffForm,email:e.target.value})}/><select className={field} value={staffForm.role} onChange={e=>setStaffForm({...staffForm,role:e.target.value})}><option>staff</option><option>manager</option><option>admin</option></select><select className={field} value={staffForm.positionId} onChange={e=>setStaffForm({...staffForm,positionId:e.target.value})}><option value="">Position</option>{positions.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><select className={field} value={staffForm.branchId} onChange={e=>setStaffForm({...staffForm,branchId:e.target.value})}><option value="">All branches</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><select className={field} value={staffForm.employmentType} onChange={e=>setStaffForm({...staffForm,employmentType:e.target.value})}><option value="full_time">Full time</option><option value="part_time">Part time</option><option value="contract">Contract</option></select><select className={field} value={staffForm.payType} onChange={e=>setStaffForm({...staffForm,payType:e.target.value})}><option value="salary">Salary</option><option value="hourly">Hourly</option></select><input className={field} type="date" value={staffForm.hireDate} onChange={e=>setStaffForm({...staffForm,hireDate:e.target.value})}/><input className={field} type="number" placeholder="Basic salary" value={staffForm.baseSalary} onChange={e=>setStaffForm({...staffForm,baseSalary:e.target.value})}/><input className={field} type="number" placeholder="Hourly rate" value={staffForm.hourlyRate} onChange={e=>setStaffForm({...staffForm,hourlyRate:e.target.value})}/></div><button className={button+" mt-4"} onClick={()=>act(()=>request("/api/v1/company/staff",{method:"POST",body:JSON.stringify(staffForm)},companyId),"Staff account and position saved")}>Save staff</button>
        <div className="mt-5 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-slate-500"><tr><th>Name</th><th>Role / position</th><th>Branch</th><th>Type</th><th>Pay</th></tr></thead><tbody>{staff.map(s=><tr key={s.user_id} className="border-t border-white/10"><td className="py-3">{[s.first_name,s.last_name].filter(Boolean).join(" ")||s.email}<div className="text-xs text-slate-500">{s.email}</div></td><td>{s.role} · {s.position_name||"No position"}</td><td>{s.branch_name||"All"}</td><td>{s.employment_type}</td><td>{s.pay_type==="hourly"?s.hourly_rate+"/hr":s.base_salary}</td></tr>)}</tbody></table></div>
        <h3 className="mb-3 mt-7 text-lg font-black">Staff leaderboard</h3><Leaderboard rows={leaders}/>
      </Panel>}

      {tab === "hr" && <div className="grid gap-5 lg:grid-cols-2">
        <Panel title="Attendance" subtitle="Staff check in and out from the app; management sees the company log."><div className="mb-4 flex gap-3"><button className={button} onClick={()=>act(()=>request("/api/v1/company/attendance/check-in",{method:"POST",body:"{}"},companyId),"Checked in")}>Check in</button><button className="rounded-xl border border-cyan-400 px-4 py-2 text-sm text-cyan-300" onClick={()=>act(()=>request("/api/v1/company/attendance/check-out",{method:"POST",body:"{}"},companyId),"Checked out")}>Check out</button></div><div className="max-h-72 space-y-2 overflow-auto">{attendance.map(a=><Mini key={a.id} title={`${a.workDate} · ${a.status}`} detail={`${a.checkInAt?new Date(a.checkInAt).toLocaleTimeString():"–"} → ${a.checkOutAt?new Date(a.checkOutAt).toLocaleTimeString():"Open"}`}/>)}</div></Panel>
        <Panel title="Leave and medical leave" subtitle="Requests and decisions notify the correct people in their mobile app."><div className="grid gap-2 sm:grid-cols-2"><select className={field} value={leaveForm.type} onChange={e=>setLeaveForm({...leaveForm,type:e.target.value})}><option value="leave">Leave</option><option value="mc">Medical leave</option></select><input className={field} type="date" value={leaveForm.startDate} onChange={e=>setLeaveForm({...leaveForm,startDate:e.target.value})}/><input className={field} type="date" value={leaveForm.endDate} onChange={e=>setLeaveForm({...leaveForm,endDate:e.target.value})}/><input className={field} placeholder="Reason" value={leaveForm.reason} onChange={e=>setLeaveForm({...leaveForm,reason:e.target.value})}/></div><button className={button+" my-3"} onClick={()=>act(()=>request("/api/v1/company/leave",{method:"POST",body:JSON.stringify(leaveForm)},companyId),"Leave request submitted")}>Request leave</button><div className="max-h-72 space-y-2 overflow-auto">{leave.map(l=><div key={l.id} className="rounded-xl border border-white/10 p-3"><b>{l.type} · {l.startDate} to {l.endDate}</b><p className="text-xs text-slate-400">{l.reason} · {l.status}</p>{l.status==="pending"&&<div className="mt-2 flex gap-3"><button className="text-xs text-emerald-300" onClick={()=>act(()=>request(`/api/v1/company/leave/${l.id}`,{method:"PATCH",body:JSON.stringify({status:"approved",paid:true})},companyId),"Leave approved")}>Approve paid</button><button className="text-xs text-red-300" onClick={()=>act(()=>request(`/api/v1/company/leave/${l.id}`,{method:"PATCH",body:JSON.stringify({status:"rejected"})},companyId),"Leave rejected")}>Reject</button></div>}</div>)}</div></Panel>
        <Panel title="Multi-date shift calendar" subtitle="Pick several dates, then publish the same shift in one action. Changes appear live for super admin, company admin and staff."><div className="grid gap-2 sm:grid-cols-2"><select className={field} value={shiftForm.userId} onChange={e=>setShiftForm({...shiftForm,userId:e.target.value})}><option value="">Select staff</option>{staff.map(s=><option key={s.user_id} value={s.user_id}>{s.first_name||s.email}</option>)}</select><div className="flex gap-2"><input className={field} type="date" value={shiftForm.shiftDate} onChange={e=>setShiftForm({...shiftForm,shiftDate:e.target.value})}/><button className="rounded-xl border border-cyan-400 px-3 text-cyan-300" onClick={()=>shiftForm.shiftDate&&!shiftDates.includes(shiftForm.shiftDate)&&setShiftDates([...shiftDates,shiftForm.shiftDate].sort())}>Add date</button></div><input className={field} type="time" value={shiftForm.startTime} onChange={e=>setShiftForm({...shiftForm,startTime:e.target.value})}/><input className={field} type="time" value={shiftForm.endTime} onChange={e=>setShiftForm({...shiftForm,endTime:e.target.value})}/></div><div className="mt-3 flex flex-wrap gap-2">{shiftDates.map(d=><button key={d} onClick={()=>setShiftDates(shiftDates.filter(x=>x!==d))} className="rounded-full bg-cyan-400/10 px-3 py-1 text-xs text-cyan-200">{d} ×</button>)}</div><button className={button+" my-3"} disabled={!shiftForm.userId||!shiftDates.length} onClick={()=>act(async()=>{await request("/api/v1/company/shifts",{method:"POST",body:JSON.stringify({...shiftForm,dates:shiftDates})},companyId);setShiftDates([])},`${shiftDates.length} shift(s) assigned`)}>Assign selected dates</button><div className="max-h-64 space-y-2 overflow-auto">{shifts.map(s=><Mini key={s.id} title={`${s.shiftDate} · ${s.startTime}–${s.endTime}`} detail={staff.find(x=>x.user_id===s.userId)?.email||s.userId}/>)}</div></Panel>
      </div>}

      {tab === "performance" && <Panel title="Weekly staff leaderboard" subtitle="Sales and customer reviews produce the ranking. Repeated bad feedback is highlighted red."><div className="grid gap-3">{leaders.map(l=><div key={l.user_id} className={`flex flex-col gap-3 rounded-xl border p-4 sm:flex-row sm:items-center sm:justify-between ${l.redFlag?"border-red-500/60 bg-red-500/10":"border-white/10 bg-white/[.03]"}`}><div className="flex items-center gap-3"><span className="text-xl font-black">#{l.rank}</span><div><b>{l.name}</b><p className="text-xs text-slate-400">{l.position||"Staff"}</p></div></div><div className="flex gap-5 text-right"><div><b>{Number(l.weekly_sales).toLocaleString()}</b><p className="text-xs text-slate-500">weekly sales</p></div><div><b><Star className="inline h-4 w-4 fill-amber-400 text-amber-400"/> {Number(l.rating).toFixed(1)}</b><p className="text-xs text-slate-500">{l.review_count} reviews</p></div></div></div>)}</div></Panel>}

      {tab === "feedback" && <Panel title="Customer feedback" subtitle="Service, staff and improvement feedback submitted from Support or the post-payment WhatsApp link appears here live."><div className="grid gap-3">{feedback.length===0&&<p className="text-sm text-slate-500">No feedback yet.</p>}{feedback.map(f=><div key={f.id} className={`rounded-xl border p-4 ${f.rating&&Number(f.rating)<=2?"border-red-500/50 bg-red-500/10":"border-white/10 bg-white/[.03]"}`}><div className="flex items-center justify-between"><b className="capitalize">{f.category} feedback</b><span className="text-xs text-slate-500">{new Date(f.created_at).toLocaleString()}</span></div><p className="mt-1 text-sm text-slate-300">{f.message}</p><p className="mt-2 text-xs text-slate-500">{f.user_name||"Customer"}{f.staff_name?` → ${f.staff_name}`:""}{f.rating?` · ${f.rating}/5 stars`:""}</p></div>)}</div></Panel>}

      {tab === "meetings" && <Panel title="Staff meetings" subtitle="Creating a meeting sends a push notification to every active employee app."><div className="grid gap-3 md:grid-cols-2"><input className={field} placeholder="Meeting title" value={meetingForm.title} onChange={e=>setMeetingForm({...meetingForm,title:e.target.value})}/><input className={field} type="datetime-local" value={meetingForm.startsAt} onChange={e=>setMeetingForm({...meetingForm,startsAt:e.target.value})}/><input className={field} placeholder="Location" value={meetingForm.location} onChange={e=>setMeetingForm({...meetingForm,location:e.target.value})}/><input className={field} placeholder="Agenda" value={meetingForm.agenda} onChange={e=>setMeetingForm({...meetingForm,agenda:e.target.value})}/></div><button className={button+" mt-4"} onClick={()=>act(()=>request("/api/v1/company/meetings",{method:"POST",body:JSON.stringify(meetingForm)},companyId),"Meeting scheduled and staff notified")}>Schedule meeting</button><div className="mt-5 grid gap-3 md:grid-cols-2">{meetings.map(m=><Mini key={m.id} title={m.title} detail={`${new Date(m.startsAt).toLocaleString()} · ${m.location||"TBA"}`}/>)}</div></Panel>}
    </main>
  </div>;
}

function Panel({title,subtitle,children}:{title:string;subtitle:string;children:any}) { return <section className="min-w-0 overflow-hidden rounded-2xl border border-white/10 bg-slate-900/70 p-4 sm:p-5"><h2 className="text-xl font-black">{title}</h2><p className="mb-5 mt-1 text-sm text-slate-400">{subtitle}</p>{children}</section> }
function Stat({icon,label,value}:{icon:any;label:string;value:any}) { return <div className="rounded-2xl border border-white/10 bg-white/[.04] p-4"><div className="mb-3 text-cyan-300">{icon}</div><b className="text-2xl">{value}</b><p className="text-xs text-slate-500">{label}</p></div> }
function Mini({title,detail}:{title:string;detail:string}) { return <div className="rounded-xl border border-white/10 bg-white/[.03] p-4"><b>{title}</b><p className="mt-1 text-xs text-slate-400">{detail}</p></div> }
function Badge({t,c}:{t:string;c:string}) { return <span className={`rounded-full px-2 py-0.5 text-[10px] font-bold ${c}`}>{t}</span> }

type Cart = Record<number,{product:Row;qty:number}>;
function PosPanel({companyId,customers,crmOn,onMsg}:{companyId:number;customers:Row[];crmOn:boolean;onMsg:(m:string)=>void}) {
  const [products,setProducts] = useState<Row[]>([]);
  const [tickets,setTickets] = useState<Row[]>([]);
  const [cart,setCart] = useState<Cart>({});
  const [charges,setCharges] = useState({discount:"0",tax:"0",serviceCharge:"0",tip:"0"});
  const [pays,setPays] = useState<{method:string;amount:string}[]>([{method:"cash",amount:""}]);
  const [customerId,setCustomerId] = useState("");
  const [prodForm,setProdForm] = useState({name:"",price:"",category:"General",stock:"0"});
  const [busy,setBusy] = useState(false);
  const [detail,setDetail] = useState<Row|null>(null);
  const load = () => { request("/api/v1/company/pos/products",{},companyId).then(setProducts).catch(()=>{}); request("/api/v1/company/pos/tickets",{},companyId).then(setTickets).catch(()=>{}); };
  useEffect(load,[companyId]);

  const addToCart = (p:Row) => setCart(c=>({...c,[p.id]:{product:p,qty:(c[p.id]?.qty||0)+1}}));
  const setQty = (id:number,qty:number) => setCart(c=>{const n={...c}; if(qty<=0)delete n[id]; else n[id]={...n[id],qty}; return n;});
  const lines = Object.values(cart);
  const subtotal = lines.reduce((s,l)=>s+Number(l.product.price)*l.qty,0);
  const num = (v:string)=>Math.max(0,Number(v)||0);
  const total = Math.max(0, subtotal - num(charges.discount) + num(charges.tax) + num(charges.serviceCharge));
  const due = total + num(charges.tip);
  const paid = pays.reduce((s,p)=>s+num(p.amount),0);
  const change = Math.max(0, paid - due);

  async function checkout() {
    if(!lines.length){onMsg("Add at least one item");return;}
    setBusy(true); onMsg("");
    try {
      const payments = pays.map(p=>({method:p.method,amount:num(p.amount)})).filter(p=>p.amount>0);
      const body = { items: lines.map(l=>({productId:l.product.id,qty:l.qty})), discount:num(charges.discount), tax:num(charges.tax), serviceCharge:num(charges.serviceCharge), tip:num(charges.tip), payments, customerId: customerId?Number(customerId):null };
      const t = await request("/api/v1/company/pos/tickets",{method:"POST",body:JSON.stringify(body)},companyId);
      onMsg(`Sale ${t.orderNo} · ${t.status}${Number(t.changeGiven)>0?` · change ${Number(t.changeGiven).toLocaleString()}`:""}`);
      setCart({}); setCharges({discount:"0",tax:"0",serviceCharge:"0",tip:"0"}); setPays([{method:"cash",amount:""}]); setCustomerId(""); load();
    } catch(e:any){ onMsg(e.message); } finally { setBusy(false); }
  }
  async function act(run:()=>Promise<any>,msg:string){ setBusy(true); onMsg(""); try{await run(); onMsg(msg); load(); if(detail)setDetail(null);}catch(e:any){onMsg(e.message);}finally{setBusy(false);} }

  return <div className="grid gap-5 lg:grid-cols-[1.3fr,1fr]">
    <Panel title="Register" subtitle="Tap products to build the sale. Supports discount, tax, service charge, tip, split & partial payment, and change.">
      <div className="mb-3 flex flex-wrap gap-2 rounded-xl border border-white/10 bg-white/[.03] p-3">
        <input className={field+" flex-1 min-w-[120px]"} placeholder="Quick add product" value={prodForm.name} onChange={e=>setProdForm({...prodForm,name:e.target.value})}/>
        <input className={field+" w-24"} type="number" placeholder="Price" value={prodForm.price} onChange={e=>setProdForm({...prodForm,price:e.target.value})}/>
        <input className={field+" w-20"} type="number" placeholder="Stock" value={prodForm.stock} onChange={e=>setProdForm({...prodForm,stock:e.target.value})}/>
        <button className={button} disabled={busy||!prodForm.name||!prodForm.price} onClick={()=>act(async()=>{await request("/api/v1/company/pos/products",{method:"POST",body:JSON.stringify(prodForm)},companyId);setProdForm({name:"",price:"",category:"General",stock:"0"});},"Product added")}>Add</button>
      </div>
      <div className="grid grid-cols-2 gap-2 sm:grid-cols-3">{products.length===0&&<p className="col-span-full text-sm text-slate-500">No products yet — add one above.</p>}{products.filter(p=>p.active!==false).map(p=><button key={p.id} onClick={()=>addToCart(p)} className="rounded-xl border border-white/10 bg-white/[.03] p-3 text-left hover:border-cyan-400/50"><b className="block truncate text-sm">{p.name}</b><span className="text-xs text-cyan-300">{Number(p.price).toLocaleString()}</span><span className="ml-2 text-[11px] text-slate-500">stk {p.stock}</span></button>)}</div>
    </Panel>

    <Panel title="Current sale" subtitle="">
      <div className="max-h-56 space-y-2 overflow-auto">{lines.length===0&&<p className="text-sm text-slate-500">Cart is empty.</p>}{lines.map(l=><div key={l.product.id} className="flex items-center gap-2 text-sm"><span className="min-w-0 flex-1 truncate">{l.product.name}</span><button className="h-6 w-6 rounded bg-white/10" onClick={()=>setQty(l.product.id,l.qty-1)}>−</button><span className="w-6 text-center">{l.qty}</span><button className="h-6 w-6 rounded bg-white/10" onClick={()=>setQty(l.product.id,l.qty+1)}>+</button><span className="w-20 text-right">{(Number(l.product.price)*l.qty).toLocaleString()}</span></div>)}</div>
      <div className="mt-3 grid grid-cols-2 gap-2">{([["discount","Discount"],["tax","Tax"],["serviceCharge","Service"],["tip","Tip"]] as const).map(([k,label])=><label key={k} className="text-xs text-slate-400">{label}<input className={field+" mt-1"} type="number" value={(charges as any)[k]} onChange={e=>setCharges({...charges,[k]:e.target.value})}/></label>)}</div>
      {crmOn&&<select className={field+" mt-3"} value={customerId} onChange={e=>setCustomerId(e.target.value)}><option value="">Walk-in (no customer)</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name}{c.phone?` · ${c.phone}`:""}</option>)}</select>}
      <div className="mt-3 space-y-2">{pays.map((p,i)=><div key={i} className="flex gap-2"><select className={field} value={p.method} onChange={e=>setPays(pays.map((x,n)=>n===i?{...x,method:e.target.value}:x))}>{["cash","card","qr","transfer","ewallet"].map(m=><option key={m} value={m}>{m}</option>)}</select><input className={field} type="number" placeholder="Amount" value={p.amount} onChange={e=>setPays(pays.map((x,n)=>n===i?{...x,amount:e.target.value}:x))}/>{pays.length>1&&<button className="rounded-xl border border-white/10 px-3 text-red-300" onClick={()=>setPays(pays.filter((_,n)=>n!==i))}>×</button>}</div>)}</div>
      <div className="mt-1 flex justify-between text-xs"><button className="text-cyan-300" onClick={()=>setPays([...pays,{method:"card",amount:""}])}>+ Split payment</button><button className="text-slate-300" onClick={()=>setPays(pays.map((p,i)=>i===0?{...p,amount:String(due)}:p))}>Exact cash</button></div>
      <div className="mt-3 rounded-xl bg-white/5 p-3 text-sm"><Row2 l="Subtotal" v={subtotal}/><Row2 l="Total due" v={due} bold/>{paid>0&&<Row2 l="Paid" v={paid}/>}{change>0&&<Row2 l="Change" v={change}/>}</div>
      <button className={button+" mt-3 w-full justify-center"} disabled={busy||!lines.length} onClick={checkout}>Charge {due.toLocaleString()}</button>
    </Panel>

    <div className="lg:col-span-2"><Panel title="Recent sales" subtitle="Tap a sale to see items, payments, and to refund or void it.">
      <div className="grid gap-2">{tickets.length===0&&<p className="text-sm text-slate-500">No sales yet.</p>}{tickets.slice(0,40).map(t=><button key={t.id} onClick={()=>request(`/api/v1/company/pos/tickets/${t.id}`,{},companyId).then(setDetail).catch(()=>{})} className="flex items-center justify-between rounded-xl border border-white/10 bg-white/[.03] p-3 text-left"><div><b>{t.orderNo}</b><p className="text-xs text-slate-400">{new Date(t.createdAt).toLocaleString()} · {t.paymentMethod||"unpaid"}</p></div><div className="text-right"><b>{Number(t.total).toLocaleString()}</b><p className={`text-xs ${t.status==="paid"?"text-emerald-300":t.status==="refunded"||t.status==="voided"?"text-red-300":"text-amber-300"}`}>{t.status}</p></div></button>)}</div>
    </Panel></div>

    {detail&&<div className="fixed inset-0 z-50 flex items-center justify-center p-4" onClick={()=>setDetail(null)}><div className="absolute inset-0 bg-black/70"/><div className="relative w-full max-w-md rounded-2xl border border-white/10 bg-slate-900 p-5" onClick={e=>e.stopPropagation()}>
      <div className="flex items-center justify-between"><b className="text-lg">{detail.orderNo}</b><span className={`text-xs ${detail.status==="paid"?"text-emerald-300":detail.status==="refunded"||detail.status==="voided"?"text-red-300":"text-amber-300"}`}>{detail.status}</span></div>
      <div className="mt-3 space-y-1 text-sm">{(detail.items||[]).map((it:Row)=><div key={it.id} className="flex justify-between"><span>{it.qty}× {it.name}</span><span>{Number(it.lineTotal).toLocaleString()}</span></div>)}</div>
      <div className="mt-3 border-t border-white/10 pt-2 text-sm"><Row2 l="Subtotal" v={Number(detail.subtotal)}/>{Number(detail.discount)>0&&<Row2 l="Discount" v={-Number(detail.discount)}/>}{Number(detail.tax)>0&&<Row2 l="Tax" v={Number(detail.tax)}/>}{Number(detail.serviceFee)>0&&<Row2 l="Service" v={Number(detail.serviceFee)}/>}{Number(detail.tip)>0&&<Row2 l="Tip" v={Number(detail.tip)}/>}<Row2 l="Total" v={Number(detail.total)} bold/><Row2 l="Paid" v={Number(detail.paidTotal)}/></div>
      {(detail.payments||[]).length>0&&<div className="mt-2 text-xs text-slate-400">{(detail.payments||[]).map((p:Row)=><div key={p.id}>{p.is_refund||p.isRefund?"↩ refund":"•"} {p.method}: {Number(p.amount).toLocaleString()}</div>)}</div>}
      {detail.status!=="voided"&&detail.status!=="refunded"&&<div className="mt-4 flex gap-2">
        <button className="flex-1 rounded-xl bg-amber-400/90 py-2.5 text-sm font-bold text-slate-950" disabled={busy} onClick={()=>{const r=prompt("Refund reason (leave blank for full refund)");act(()=>request(`/api/v1/company/pos/tickets/${detail.id}/refund`,{method:"POST",body:JSON.stringify({reason:r||""})},companyId),"Refunded")}}>Refund</button>
        <button className="flex-1 rounded-xl bg-red-500/90 py-2.5 text-sm font-bold text-white" disabled={busy} onClick={()=>{const r=prompt("Void reason");if(r!==null)act(()=>request(`/api/v1/company/pos/tickets/${detail.id}/void`,{method:"POST",body:JSON.stringify({reason:r})},companyId),"Voided")}}>Void</button>
      </div>}
      <button className="mt-3 w-full text-sm text-slate-400" onClick={()=>setDetail(null)}>Close</button>
    </div></div>}
  </div>;
}
function Row2({l,v,bold}:{l:string;v:number;bold?:boolean}) { return <div className={`flex justify-between ${bold?"font-bold":""}`}><span className="text-slate-400">{l}</span><span>{v.toLocaleString()}</span></div> }

const TABLE_COLOR:Record<string,string> = { available:"border-emerald-400/50 bg-emerald-400/5", occupied:"border-amber-400/60 bg-amber-400/10", reserved:"border-cyan-400/50 bg-cyan-400/5" };
function TablesPanel({companyId,onMsg}:{companyId:number;onMsg:(m:string)=>void}) {
  const [tables,setTables] = useState<Row[]>([]);
  const [products,setProducts] = useState<Row[]>([]);
  const [form,setForm] = useState({name:"",area:"",seats:"2"});
  const [open,setOpen] = useState<Row|null>(null);
  const [pay,setPay] = useState({method:"cash"});
  const [busy,setBusy] = useState(false);
  const load = () => { request("/api/v1/company/restaurant/tables",{},companyId).then(setTables).catch(()=>{}); request("/api/v1/company/pos/products",{},companyId).then(setProducts).catch(()=>{}); };
  useEffect(load,[companyId]);
  const openTable = async (t:Row) => { setBusy(true); try { const tk = await request(`/api/v1/company/restaurant/tables/${t.id}/open`,{method:"POST",body:"{}"},companyId); await refreshDrawer(t.id); load(); } catch(e:any){onMsg(e.message);} finally{setBusy(false);} };
  const refreshDrawer = async (id:number) => { const d = await request(`/api/v1/company/restaurant/tables/${id}`,{},companyId); setOpen(d); };
  const addItem = async (productId:number) => { if(!open?.ticket) return; setBusy(true); try { await request(`/api/v1/company/pos/tickets/${open.ticket.id}/items`,{method:"POST",body:JSON.stringify({items:[{productId,qty:1}]})},companyId); await refreshDrawer(open.id); } catch(e:any){onMsg(e.message);} finally{setBusy(false);} };
  const settle = async () => { if(!open?.ticket) return; setBusy(true); try { const due = Number(open.ticket.total); await request(`/api/v1/company/pos/tickets/${open.ticket.id}/settle`,{method:"POST",body:JSON.stringify({payments:[{method:pay.method,amount:due}]})},companyId); onMsg(`Table ${open.name} settled (${due.toLocaleString()})`); setOpen(null); load(); } catch(e:any){onMsg(e.message);} finally{setBusy(false);} };
  const freeTable = async () => { if(!open) return; setBusy(true); try { await request(`/api/v1/company/restaurant/tables/${open.id}/close`,{method:"POST",body:"{}"},companyId); setOpen(null); load(); } catch(e:any){onMsg(e.message);} finally{setBusy(false);} };

  return <Panel title="Tables & floor plan" subtitle="Green = free, amber = occupied. Tap a table to open a tab, add items (they fire to the kitchen), then settle. Print each table's QR for self-ordering.">
    <div className="mb-4 flex flex-wrap gap-2"><input className={field+" w-32"} placeholder="Table name/no." value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input className={field+" w-28"} placeholder="Area" value={form.area} onChange={e=>setForm({...form,area:e.target.value})}/><input className={field+" w-20"} type="number" placeholder="Seats" value={form.seats} onChange={e=>setForm({...form,seats:e.target.value})}/><button className={button} disabled={busy||!form.name} onClick={async()=>{try{await request("/api/v1/company/restaurant/tables",{method:"POST",body:JSON.stringify(form)},companyId);setForm({name:"",area:"",seats:"2"});onMsg("Table added");load();}catch(e:any){onMsg(e.message);}}}><Plus className="mr-1 inline h-4 w-4"/>Add table</button></div>
    <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{tables.length===0&&<p className="col-span-full text-sm text-slate-500">No tables yet.</p>}{tables.map(t=><button key={t.id} onClick={()=>refreshDrawer(t.id)} className={`rounded-2xl border p-4 text-left ${TABLE_COLOR[t.status]||"border-white/10 bg-white/[.03]"}`}><div className="flex items-center justify-between"><b className="text-lg">{t.name}</b><span className="text-[11px] uppercase text-slate-400">{t.status}</span></div><p className="mt-1 text-xs text-slate-400">{t.area||"—"} · {t.seats} seats</p>{t.current_ticket_id&&<p className="mt-2 text-sm text-amber-200">{Number(t.open_items||0)} item(s) · {Number(t.open_total||0).toLocaleString()}</p>}</button>)}</div>

    {open&&<div className="fixed inset-0 z-50 flex items-center justify-center p-4" onClick={()=>setOpen(null)}><div className="absolute inset-0 bg-black/70"/><div className="relative flex max-h-[85vh] w-full max-w-lg flex-col rounded-2xl border border-white/10 bg-slate-900 p-5" onClick={e=>e.stopPropagation()}>
      <div className="flex items-center justify-between"><b className="text-lg">Table {open.name}</b><a className="text-xs text-cyan-300 underline" href={`/api/v1/company/restaurant/tables/${open.id}/qr`} target="_blank" rel="noreferrer">Print QR</a></div>
      {!open.ticket&&<button className={button+" mt-4"} disabled={busy} onClick={()=>openTable(open)}>Open tab for this table</button>}
      {open.ticket&&<>
        <p className="mt-1 text-xs text-slate-400">{open.ticket.orderNo} · {open.ticket.status}</p>
        <div className="mt-3 max-h-40 space-y-1 overflow-auto text-sm">{(open.ticket.items||[]).length===0&&<p className="text-slate-500">No items yet.</p>}{(open.ticket.items||[]).map((it:Row)=><div key={it.id} className="flex justify-between"><span>{it.qty}× {it.name} <span className="text-[10px] text-slate-500">{it.station}·{it.status}</span></span><span>{Number(it.lineTotal).toLocaleString()}</span></div>)}</div>
        <div className="mt-3 border-t border-white/10 pt-2"><Row2 l="Total" v={Number(open.ticket.total)} bold/></div>
        <p className="mt-3 text-xs text-slate-400">Add items:</p>
        <div className="mt-1 grid max-h-40 grid-cols-2 gap-2 overflow-auto sm:grid-cols-3">{products.filter(p=>p.active!==false).map(p=><button key={p.id} disabled={busy} onClick={()=>addItem(p.id)} className="rounded-lg border border-white/10 bg-white/[.03] p-2 text-left text-xs hover:border-cyan-400/50"><b className="block truncate">{p.name}</b><span className="text-cyan-300">{Number(p.price).toLocaleString()}</span></button>)}</div>
        <div className="mt-4 flex items-center gap-2"><select className={field+" w-32"} value={pay.method} onChange={e=>setPay({method:e.target.value})}>{["cash","card","qr","transfer","ewallet"].map(m=><option key={m} value={m}>{m}</option>)}</select><button className={button+" flex-1 justify-center"} disabled={busy||!(open.ticket.items||[]).length} onClick={settle}>Settle {Number(open.ticket.total).toLocaleString()}</button></div>
        <button className="mt-2 text-xs text-red-300" onClick={freeTable}>Free table without charge</button>
      </>}
      <button className="mt-3 text-sm text-slate-400" onClick={()=>setOpen(null)}>Close</button>
    </div></div>}
  </Panel>;
}

const KDS_NEXT:Record<string,string> = { new:"preparing", preparing:"ready", ready:"served" };
const KDS_LABEL:Record<string,string> = { new:"Start", preparing:"Ready", ready:"Serve" };
function KdsPanel({companyId,onMsg}:{companyId:number;onMsg:(m:string)=>void}) {
  const [items,setItems] = useState<Row[]>([]);
  const [station,setStation] = useState("");
  const load = () => request(`/api/v1/company/restaurant/kds${station?`?station=${station}`:""}`,{},companyId).then(setItems).catch(()=>{});
  useEffect(()=>{ load(); const t=setInterval(load,4000); const es=new EventSource(`/api/v1/company/live?companyId=${companyId}`); es.addEventListener("change",load); return ()=>{clearInterval(t);es.close();}; },[companyId,station]);
  const advance = async (it:Row) => { const next=KDS_NEXT[it.status]; if(!next) return; try{ await request(`/api/v1/company/restaurant/kds/${it.id}`,{method:"PATCH",body:JSON.stringify({status:next})},companyId); load(); }catch(e:any){onMsg(e.message);} };
  const cols = ["new","preparing","ready"];
  return <Panel title="Kitchen display" subtitle="Live order queue. Tap a ticket to move it new → preparing → ready → served. Drinks route to Bar, desserts to Dessert.">
    <div className="mb-4 flex gap-2">{[["","All"],["kitchen","Kitchen"],["bar","Bar"],["dessert","Dessert"]].map(([k,label])=><button key={k} onClick={()=>setStation(k)} className={`rounded-full px-3 py-1.5 text-sm ${station===k?"bg-cyan-400 font-bold text-slate-950":"bg-white/5 text-slate-300"}`}>{label}</button>)}</div>
    <div className="grid gap-3 sm:grid-cols-3">{cols.map(col=><div key={col}><h3 className="mb-2 text-sm font-black uppercase tracking-wider text-slate-400">{col} <span className="text-slate-600">({items.filter(i=>i.status===col).length})</span></h3><div className="space-y-2">{items.filter(i=>i.status===col).map(it=><button key={it.id} onClick={()=>advance(it)} className={`w-full rounded-xl border p-3 text-left ${col==="new"?"border-red-400/40 bg-red-500/5":col==="preparing"?"border-amber-400/40 bg-amber-400/5":"border-emerald-400/40 bg-emerald-400/5"}`}><div className="flex justify-between"><b className="text-sm">{it.qty}× {it.name}</b><span className="text-[10px] uppercase text-slate-500">{it.station}</span></div><p className="mt-1 text-xs text-slate-400">{it.order_no}{it.table_number?` · T${it.table_number}`:""}</p><span className="mt-2 inline-block rounded bg-white/10 px-2 py-0.5 text-[11px]">{KDS_LABEL[it.status]||"Done"} →</span></button>)}{items.filter(i=>i.status===col).length===0&&<p className="text-xs text-slate-600">Empty</p>}</div></div>)}</div>
  </Panel>;
}
function Leaderboard({rows}:{rows:Row[]}) { return <div className="grid gap-3">{rows.length===0&&<p className="text-sm text-slate-500">No ranked staff yet.</p>}{rows.map(l=><div key={l.user_id} className={`flex flex-col gap-3 rounded-xl border p-4 sm:flex-row sm:items-center sm:justify-between ${l.redFlag?"border-red-500/60 bg-red-500/10":"border-white/10 bg-white/[.03]"}`}><div className="flex items-center gap-3"><span className="text-xl font-black">#{l.rank}</span><div><b>{l.name}</b><p className="text-xs text-slate-400">{l.position||"Staff"}</p></div></div><div className="flex gap-5 text-right"><div><b>{Number(l.weekly_sales).toLocaleString()}</b><p className="text-xs text-slate-500">weekly sales</p></div><div><b><Star className="inline h-4 w-4 fill-amber-400 text-amber-400"/> {Number(l.rating).toFixed(1)}</b><p className="text-xs text-slate-500">{l.review_count} reviews</p></div></div></div>)}</div> }
function OperationsPanel({settings,setSettings,onSave}:{settings:any;setSettings:(v:any)=>void;onSave:()=>void}) {
  const loyalty=settings.loyalty||{pointsSpendRp:1000,rewardsEnabled:true,tiers:[]}; const services=settings.services||{}; const booking=settings.booking||{areas:[]};
  const setL=(patch:any)=>setSettings({...settings,loyalty:{...loyalty,...patch}}); const setService=(key:string,value:boolean)=>setSettings({...settings,services:{...services,[key]:value}});
  const updateTier=(i:number,patch:any)=>setL({tiers:(loyalty.tiers||[]).map((t:any,n:number)=>n===i?{...t,...patch}:t)});
  const updateArea=(i:number,patch:any)=>setSettings({...settings,booking:{...booking,areas:(booking.areas||[]).map((a:any,n:number)=>n===i?{...a,...patch}:a)}});
  return <div className="grid gap-5 lg:grid-cols-2">
    <Panel title="Loyalty rules" subtitle="Points are awarded automatically at checkout. Every number now shows what it controls.">
      <label className="block text-xs text-slate-400">RP spending needed to earn 1 point<input className={field+" mt-1"} type="number" min="1" value={loyalty.pointsSpendRp||1000} onChange={e=>setL({pointsSpendRp:Math.max(1,Number(e.target.value)||1)})}/><span className="mt-1 block text-[11px] text-slate-500">Example: 1,000 means every RP 1,000 spent earns 1 point.</span></label>
      <label className="mt-3 flex items-center gap-3 rounded-xl border border-white/10 p-3"><input type="checkbox" checked={loyalty.rewardsEnabled!==false} onChange={e=>setL({rewardsEnabled:e.target.checked})}/> Enable reward redemption</label>
      <p className="mt-1 text-[11px] text-slate-500">Turn this off to hide reward redemption from members.</p>
      <div className="mt-4 space-y-3">{(loyalty.tiers||[]).map((t:any,i:number)=><div key={i} className="rounded-xl border border-white/10 p-3">
        <p className="mb-3 text-xs font-black uppercase tracking-wider text-cyan-300">Tier {i + 1}</p>
        <div className="grid gap-3 sm:grid-cols-2">
          <label className="text-xs text-slate-400">Tier name<input className={field+" mt-1"} placeholder="Example: Silver" value={t.name||""} onChange={e=>updateTier(i,{name:e.target.value})}/></label>
          <label className="text-xs text-slate-400">Points required to reach tier<input className={field+" mt-1"} type="number" min="0" placeholder="Example: 500" value={t.minPoints||0} onChange={e=>updateTier(i,{minPoints:Math.max(0,Number(e.target.value)||0)})}/></label>
          <label className="text-xs text-slate-400">Member discount (%)<input className={field+" mt-1"} type="number" min="0" max="100" placeholder="Example: 2" value={t.discountPercent||0} onChange={e=>updateTier(i,{discountPercent:Math.max(0,Math.min(100,Number(e.target.value)||0))})}/><span className="mt-1 block text-[10px] text-slate-500">Enter 2 for 2%. Enter 0 for none.</span></label>
          <label className="text-xs text-slate-400">Store gift value (RP)<input className={field+" mt-1"} type="number" min="0" placeholder="Example: 50000" value={t.freeRp||0} onChange={e=>updateTier(i,{freeRp:Math.max(0,Number(e.target.value)||0)})}/><span className="mt-1 block text-[10px] text-slate-500">Enter 50,000 for an RP 50,000 gift.</span></label>
        </div>
        <label className="mt-3 block text-xs text-slate-400">Other tier benefits<input className={field+" mt-1"} placeholder="Example: Priority booking, birthday gift" value={(t.benefits||[]).join(", ")} onChange={e=>updateTier(i,{benefits:e.target.value.split(",").map(x=>x.trim()).filter(Boolean)})}/><span className="mt-1 block text-[10px] text-slate-500">Separate multiple benefits with commas.</span></label>
        <p className="mt-3 rounded-lg bg-white/5 px-3 py-2 text-[11px] text-slate-400"><b>{t.name||`Tier ${i+1}`}</b>: starts at {Number(t.minPoints||0).toLocaleString()} points · {Number(t.discountPercent||0)}% discount · {Number(t.freeRp||0)>0?`RP ${Number(t.freeRp).toLocaleString()} store gift`:"no store gift"}</p>
        <button className="mt-3 text-left text-xs text-red-300" onClick={()=>setL({tiers:loyalty.tiers.filter((_:any,n:number)=>n!==i)})}>Remove tier</button>
      </div>)}</div>
      <button className="mt-3 text-sm font-bold text-cyan-300" onClick={()=>setL({tiers:[...(loyalty.tiers||[]),{name:`Tier ${(loyalty.tiers||[]).length+1}`,minPoints:0,discountPercent:0,freeRp:0,benefits:[]}]})}>+ Add tier</button>
      <button className={button+" mt-4 w-full justify-center"} onClick={onSave}>Save loyalty settings</button>
    </Panel>
    <Panel title="AI channels and service switches" subtitle="Turn each company function on or off. WhatsApp and Telegram can be linked independently from the company app."><div className="grid gap-2 sm:grid-cols-2">{[["booking","Booking"],["faq","FAQ replies"],["songRequests","Song request"],["bottleKeep","Bottle keep"],["aiWhatsApp","AI WhatsApp"],["aiTelegram","AI Telegram"],["reminders","Automated reminders"],["retail","Retail mode"]].map(([key,label])=><label key={key} className="flex items-center gap-3 rounded-xl border border-white/10 bg-white/[.03] p-3"><input type="checkbox" checked={!!services[key]} onChange={e=>setService(key,e.target.checked)}/>{label}</label>)}</div><div className="mt-4 rounded-xl bg-cyan-400/5 p-4 text-sm text-slate-300"><b>Channel connection</b><p className="mt-1 text-xs text-slate-400">Company admins can open their company app, choose WhatsApp or Telegram, scan the displayed QR code, and then configure reminders, FAQ, booking, song requests and bottle keeping here.</p></div></Panel>
    <Panel title="Booking areas and floor plans" subtitle="Create rooms or areas, upload a floor-plan URL, list tables, and set operating times. WhatsApp booking uses the same company configuration."><div className="space-y-3">{(booking.areas||[]).map((a:any,i:number)=><div key={i} className="grid gap-2 rounded-xl border border-white/10 p-3 sm:grid-cols-2"><input className={field} placeholder="Area / room name" value={a.name||""} onChange={e=>updateArea(i,{name:e.target.value})}/><input className={field} placeholder="Level" value={a.level||""} onChange={e=>updateArea(i,{level:e.target.value})}/><input className={field+" sm:col-span-2"} placeholder="Floor plan image URL" value={a.imageUrl||""} onChange={e=>updateArea(i,{imageUrl:e.target.value})}/><input className={field+" sm:col-span-2"} placeholder="Tables / rooms, comma separated" value={(a.tables||[]).join(", ")} onChange={e=>updateArea(i,{tables:e.target.value.split(",").map(x=>x.trim()).filter(Boolean)})}/><input className={field} type="time" value={a.openTime||"17:00"} onChange={e=>updateArea(i,{openTime:e.target.value})}/><input className={field} type="time" value={a.closeTime||"02:00"} onChange={e=>updateArea(i,{closeTime:e.target.value})}/><button className="text-left text-xs text-red-300" onClick={()=>setSettings({...settings,booking:{...booking,areas:booking.areas.filter((_:any,n:number)=>n!==i)}})}>Remove area</button></div>)}</div><button className="mt-3 text-sm font-bold text-cyan-300" onClick={()=>setSettings({...settings,booking:{...booking,areas:[...(booking.areas||[]),{name:"New area",level:"Ground",imageUrl:"",tables:[],openTime:"17:00",closeTime:"02:00"}]}})}>+ Add area or room</button></Panel>
    <Panel title="Website and app provisioning" subtitle="The selected merchant receives a tenant login URL while custom domain and store builds are prepared."><p className="rounded-xl bg-white/5 p-4 text-sm">Temporary tenant login: <a className="text-cyan-300 underline" href="/bridgexpos/login">BridgeXPOS merchant login</a></p><p className="mt-3 text-xs text-slate-400">Website, backend and app design use the same enabled modules and can follow the Reborn app layout as the starting template.</p><button className={button+" mt-5"} onClick={onSave}>Save all operation settings</button></Panel>
  </div>
}
